### ISSUE TITLE
Raw results

### ISSUE THREAD

**Issue by ottenhoff** [berezovskyi/lambda-test#2]
Can you post the raw results? I am most interested in Java cold start times and interested in outliers (e.g., 10+ second launches) .... the averages are helpful but API Gateway has a 10 second time limit so outliers are very important for use of Java lambdas

**Comment by berezovskyi** [comment]
Unfortunately, didn't have chance to write a matching Lambda function using Java. Measured startup time solely on my VM. You can re-run the measurements yourself (`test.sh` in the root). Also, you don't pay for the time AWS is finding you an instance to run - you only pay after the AWS starts spinning a JVM up for you. There the startup time variance should be minimal, far less than a second.

**Comment by berezovskyi** [comment]
On AWS, I used standard "blueprints" for Node.js and Python (I did move dynamodb initialization out of the handler in Python code though). This is my attempt to mimic their code in Java: https://github.com/berezovskyi/lambda-test-java

**Comment by berezovskyi** [comment]
Added java fn to the test and replaced the average duration metrics with maximum duration: https://github.com/berezovskyi/lambda-test#cloudwatch-stats-for-sample-microservices-deployed-python--nodejs
